version: '3'

services:
  gateway_service:
    build: ./gateway
    volumes:
      - ./gateway:/usr/src/gateway
    ports:
      - 8081:8081
    depends_on:
      - math_service
      - random_service
      - string_service

  math_service:
    build: ./math_py
    volumes:
      - ./math_py:/usr/src/math_py
    ports:
      - 8080:8080

  string_service:
    build: ./string_rust
    volumes:
      - ./string_rust:/usr/src/string_rust
    ports:
      - 5000:5000

  random_service:
    build: ./random_py
    volumes:
      - ./random_py:/usr/src/random_py
    ports:
      - 8082:8082
